FROM alpine:latest
LABEL author yeqing.run
RUN sed -i 's~dl-cdn.alpinelinux.org~mirrors.aliyun.com~' /etc/apk/repositories \
    && apk update \
    && apk add --no-cache tzdata php7-pear php7-common php7-curl php7-dev php7 php7-fpm php7-json php7-mbstring php7-pecl-mcrypt php7-pdo_mysql php7-opcache php7-zip php7-intl php7-gd php7-xml php7-calendar php7-ctype php7-dom php7-exif php7-fileinfo php7-ftp php7-gettext php7-iconv php7-mysqli php7-pcntl php7-phar php7-posix php7-session php7-shmop php7-simplexml php7-sockets php7-sysvmsg php7-sysvsem php7-sysvshm php7-tokenizer php7-wddx php7-xmlreader php7-xmlwriter php7-xsl nginx \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && mkdir /run/nginx \
    && cd /home \
    && apk del tzdata \
    && rm -rf /var/cache/apk/* \
    && rm -rf /root/.cache \
    && rm -rf /tmp/*
WORKDIR /
CMD php-fpm7 && nginx && sh && exit
