FROM alpine:3.8
RUN sed -i 's~dl-cdn.alpinelinux.org~mirrors.aliyun.com~' /etc/apk/repositories \
    && apk --update --no-cache add php7-pear php7-common php7-curl php7-dev php7 php7-fpm php7-json php7-mbstring php7-pdo_mysql php7-opcache php7-zip php7-intl php7-gd php7-xml php7-calendar php7-ctype php7-dom php7-exif php7-fileinfo php7-ftp php7-gettext php7-iconv php7-mysqli php7-pcntl php7-phar php7-posix php7-session php7-shmop php7-simplexml php7-sockets php7-sysvmsg php7-sysvsem php7-sysvshm php7-tokenizer php7-wddx php7-xmlreader php7-xmlwriter php7-xsl nginx \
    && rm -rf /var/cache/apk/*
